# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if and (.Capabilities.APIVersions.Has "uds.dev/v1alpha1") .Values.exemptionEnabled }}
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: metallb
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - RestrictHostPorts
        - DropAllCapabilities
        - RestrictHostPorts
        - RequireNonRootUser
        - DisallowHostNamespaces
        - RestrictCapabilities
      matcher:
        namespace: metallb-system
        name: "^metallb-speaker.*"
{{- end }}
