# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

controller:
  image:
    repository: cgr.dev/defenseunicorns.com/metallb-controller
    tag: v0.16.1

speaker:
  image:
    repository: cgr.dev/defenseunicorns.com/metallb-speaker
    tag: v0.16.1
