# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.passthroughIngress.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: passthrough-ingressgateway
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.passthroughIngress.ipAddressPool }}/32
  {{- if or .Values.passthroughIngress.namespace .Values.passthroughIngress.matchLabels }}
  serviceAllocation:
    priority: 50
    {{- if .Values.passthroughIngress.namespace }}
    namespaces:
      - {{ .Values.passthroughIngress.namespace }}
    {{- end }}
    {{- if .Values.passthroughIngress.matchLabels }}
    serviceSelectors:
      - matchLabels:
          {{- toYaml .Values.passthroughIngress.matchLabels | nindent 10 }}
    {{- end }}
  {{- end }}
{{- end }}
