# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: CI Doc Shim

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

jobs:
  validate:
    strategy:
      matrix:
        type: [install, upgrade]
        flavor: [upstream, unicorn, registry1]
    uses: defenseunicorns/uds-common/.github/workflows/callable-ci-docs-shim.yaml@6ee968a8f79c08b87ceeae7e1e69423f0e1db3c2 # v1.15.1
    with:
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.
